# Workshop1: Python and Useful Packages
## Numpy
Numpy allows us to manipulate arrays

In [2]:
import numpy

# the following is an initialzation of an array
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)

In [3]:
# this return the dimension of the array
myarray.shape

(2, 3)

In [4]:
# print row of an array
myarray[1]

array([3, 4, 5])

In [5]:
# print column of an array 
myarray[:, 2]

array([3, 5])

## Pandas

In [6]:
import pandas as pd

# initialization of Series
my_list = [1, 2, 3, 1]
my_row_names = ["Ann", "Ben", "Clay", "Alice"]
my_series = pd.Series(my_list, my_row_names)

In [7]:
my_series

Ann      1
Ben      2
Clay     3
Alice    1
dtype: int64

In [8]:
my_series[1]

2

In [9]:
# shows the indices and values
print(my_series.index)
print(my_series.values)

Index(['Ann', 'Ben', 'Clay', 'Alice'], dtype='object')
[1 2 3 1]


In [10]:
# series can be used as dictionary
my_series["Ann"]

1

In [16]:
my_series["Ann":]

Ann      1
Ben      2
Clay     3
Alice    1
dtype: int64